server:
  port: 10010   #端口

spring:
  cloud:
    nacos:
      server-addr: localhost:8848   #注册到nacos
    gateway:
      routes:   #路由
        - id: order-service
          uri: lb://orderservice   #对orderservice负载均衡，也可以指定一个实例服务
          predicates:
            - Path=/order/**    #按路径路由

        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
  application:
    name: gateway     #服务名