server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.liuxing.order.pojo
  configuration:
    map-underscore-to-camel-case: true

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      username: ""
      password: ""
      context-path: ""
      ##if use MSE Nacos with auth, mutex with username/password attribute
      #access-key: ""
      #secret-key: ""
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default

logging:
  level:
    com.*: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
