server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379



mybatis:
  type-aliases-package: com.liuxing.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.liuxing.user.*: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
